// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.1
// source: btc/btc.proto

package btc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PubKeyPost Input Public Key
type PubKeyPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key string `protobuf:"bytes,1,opt,name=Key,json=key,proto3" json:"Key,omitempty"`
}

func (x *PubKeyPost) Reset() {
	*x = PubKeyPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_btc_btc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PubKeyPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PubKeyPost) ProtoMessage() {}

func (x *PubKeyPost) ProtoReflect() protoreflect.Message {
	mi := &file_btc_btc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PubKeyPost.ProtoReflect.Descriptor instead.
func (*PubKeyPost) Descriptor() ([]byte, []int) {
	return file_btc_btc_proto_rawDescGZIP(), []int{0}
}

func (x *PubKeyPost) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// MnemonicPost Input Mnemonic
type MnemonicPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainID  uint64 `protobuf:"varint,1,opt,name=ChainID,json=chain_id,proto3" json:"ChainID,omitempty"`
	Mnemonic string `protobuf:"bytes,2,opt,name=Mnemonic,json=mnemonic,proto3" json:"Mnemonic,omitempty"`
	Pass     string `protobuf:"bytes,3,opt,name=Pass,json=pass,proto3" json:"Pass,omitempty"`
	Account  uint32 `protobuf:"varint,4,opt,name=Account,json=account,proto3" json:"Account,omitempty"`
	External bool   `protobuf:"varint,5,opt,name=External,json=external,proto3" json:"External,omitempty"`
	Address  uint32 `protobuf:"varint,6,opt,name=Address,json=address,proto3" json:"Address,omitempty"`
}

func (x *MnemonicPost) Reset() {
	*x = MnemonicPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_btc_btc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MnemonicPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MnemonicPost) ProtoMessage() {}

func (x *MnemonicPost) ProtoReflect() protoreflect.Message {
	mi := &file_btc_btc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MnemonicPost.ProtoReflect.Descriptor instead.
func (*MnemonicPost) Descriptor() ([]byte, []int) {
	return file_btc_btc_proto_rawDescGZIP(), []int{1}
}

func (x *MnemonicPost) GetChainID() uint64 {
	if x != nil {
		return x.ChainID
	}
	return 0
}

func (x *MnemonicPost) GetMnemonic() string {
	if x != nil {
		return x.Mnemonic
	}
	return ""
}

func (x *MnemonicPost) GetPass() string {
	if x != nil {
		return x.Pass
	}
	return ""
}

func (x *MnemonicPost) GetAccount() uint32 {
	if x != nil {
		return x.Account
	}
	return 0
}

func (x *MnemonicPost) GetExternal() bool {
	if x != nil {
		return x.External
	}
	return false
}

func (x *MnemonicPost) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

// SeedPost Input Seed & Path
type SeedPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainID  uint64 `protobuf:"varint,1,opt,name=ChainID,json=chain_id,proto3" json:"ChainID,omitempty"`
	Seed     string `protobuf:"bytes,2,opt,name=Seed,json=seed,proto3" json:"Seed,omitempty"`
	Account  uint32 `protobuf:"varint,3,opt,name=Account,json=account,proto3" json:"Account,omitempty"`
	External bool   `protobuf:"varint,4,opt,name=External,json=external,proto3" json:"External,omitempty"`
	Address  uint32 `protobuf:"varint,5,opt,name=Address,json=address,proto3" json:"Address,omitempty"`
}

func (x *SeedPost) Reset() {
	*x = SeedPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_btc_btc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeedPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeedPost) ProtoMessage() {}

func (x *SeedPost) ProtoReflect() protoreflect.Message {
	mi := &file_btc_btc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeedPost.ProtoReflect.Descriptor instead.
func (*SeedPost) Descriptor() ([]byte, []int) {
	return file_btc_btc_proto_rawDescGZIP(), []int{2}
}

func (x *SeedPost) GetChainID() uint64 {
	if x != nil {
		return x.ChainID
	}
	return 0
}

func (x *SeedPost) GetSeed() string {
	if x != nil {
		return x.Seed
	}
	return ""
}

func (x *SeedPost) GetAccount() uint32 {
	if x != nil {
		return x.Account
	}
	return 0
}

func (x *SeedPost) GetExternal() bool {
	if x != nil {
		return x.External
	}
	return false
}

func (x *SeedPost) GetAddress() uint32 {
	if x != nil {
		return x.Address
	}
	return 0
}

// MultiSigPost input required & pubk list
type MultiSigPost struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainID    uint64   `protobuf:"varint,1,opt,name=ChainID,json=chain_id,proto3" json:"ChainID,omitempty"`
	Required   uint64   `protobuf:"varint,2,opt,name=required,proto3" json:"required,omitempty"`
	PublicKeys []string `protobuf:"bytes,3,rep,name=public_keys,proto3" json:"public_keys,omitempty"`
}

func (x *MultiSigPost) Reset() {
	*x = MultiSigPost{}
	if protoimpl.UnsafeEnabled {
		mi := &file_btc_btc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiSigPost) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiSigPost) ProtoMessage() {}

func (x *MultiSigPost) ProtoReflect() protoreflect.Message {
	mi := &file_btc_btc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiSigPost.ProtoReflect.Descriptor instead.
func (*MultiSigPost) Descriptor() ([]byte, []int) {
	return file_btc_btc_proto_rawDescGZIP(), []int{3}
}

func (x *MultiSigPost) GetChainID() uint64 {
	if x != nil {
		return x.ChainID
	}
	return 0
}

func (x *MultiSigPost) GetRequired() uint64 {
	if x != nil {
		return x.Required
	}
	return 0
}

func (x *MultiSigPost) GetPublicKeys() []string {
	if x != nil {
		return x.PublicKeys
	}
	return nil
}

// Segwit Segwit Address Struct
type Segwit struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=Address,json=address,proto3" json:"Address,omitempty"`
	Private string `protobuf:"bytes,2,opt,name=Private,json=private,proto3" json:"Private,omitempty"`
	Public  string `protobuf:"bytes,3,opt,name=Public,json=public,proto3" json:"Public,omitempty"`
}

func (x *Segwit) Reset() {
	*x = Segwit{}
	if protoimpl.UnsafeEnabled {
		mi := &file_btc_btc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Segwit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Segwit) ProtoMessage() {}

func (x *Segwit) ProtoReflect() protoreflect.Message {
	mi := &file_btc_btc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Segwit.ProtoReflect.Descriptor instead.
func (*Segwit) Descriptor() ([]byte, []int) {
	return file_btc_btc_proto_rawDescGZIP(), []int{4}
}

func (x *Segwit) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Segwit) GetPrivate() string {
	if x != nil {
		return x.Private
	}
	return ""
}

func (x *Segwit) GetPublic() string {
	if x != nil {
		return x.Public
	}
	return ""
}

// SegwitResponse Return Generate private key | public key | address
type SegwitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string  `protobuf:"bytes,1,opt,name=Message,json=message,proto3" json:"Message,omitempty"`
	Data    *Segwit `protobuf:"bytes,2,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
}

func (x *SegwitResponse) Reset() {
	*x = SegwitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_btc_btc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SegwitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SegwitResponse) ProtoMessage() {}

func (x *SegwitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_btc_btc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SegwitResponse.ProtoReflect.Descriptor instead.
func (*SegwitResponse) Descriptor() ([]byte, []int) {
	return file_btc_btc_proto_rawDescGZIP(), []int{5}
}

func (x *SegwitResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SegwitResponse) GetData() *Segwit {
	if x != nil {
		return x.Data
	}
	return nil
}

// MultiSig MultiSig Address Struct
type MultiSig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=Address,json=address,proto3" json:"Address,omitempty"`
	Script  string `protobuf:"bytes,2,opt,name=Script,json=script,proto3" json:"Script,omitempty"`
}

func (x *MultiSig) Reset() {
	*x = MultiSig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_btc_btc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiSig) ProtoMessage() {}

func (x *MultiSig) ProtoReflect() protoreflect.Message {
	mi := &file_btc_btc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiSig.ProtoReflect.Descriptor instead.
func (*MultiSig) Descriptor() ([]byte, []int) {
	return file_btc_btc_proto_rawDescGZIP(), []int{6}
}

func (x *MultiSig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *MultiSig) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

// MultiSigResponse return MultiSig address
type MultiSigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string    `protobuf:"bytes,1,opt,name=Message,json=message,proto3" json:"Message,omitempty"`
	Data    *MultiSig `protobuf:"bytes,2,opt,name=Data,json=data,proto3" json:"Data,omitempty"`
}

func (x *MultiSigResponse) Reset() {
	*x = MultiSigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_btc_btc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MultiSigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultiSigResponse) ProtoMessage() {}

func (x *MultiSigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_btc_btc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultiSigResponse.ProtoReflect.Descriptor instead.
func (*MultiSigResponse) Descriptor() ([]byte, []int) {
	return file_btc_btc_proto_rawDescGZIP(), []int{7}
}

func (x *MultiSigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MultiSigResponse) GetData() *MultiSig {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_btc_btc_proto protoreflect.FileDescriptor

var file_btc_btc_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x74, 0x63, 0x2f, 0x62, 0x74, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x62, 0x74, 0x63, 0x1a, 0x10, 0x62, 0x74, 0x63, 0x2f, 0x67, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x0a, 0x50, 0x75, 0x62, 0x4b, 0x65, 0x79,
	0x50, 0x6f, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0xa9, 0x01, 0x0a, 0x0c, 0x4d, 0x6e, 0x65, 0x6d, 0x6f,
	0x6e, 0x69, 0x63, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f,
	0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4d, 0x6e, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x6e, 0x65, 0x6d, 0x6f, 0x6e, 0x69, 0x63, 0x12, 0x12,
	0x0a, 0x04, 0x50, 0x61, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x65, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x22, 0x89, 0x01, 0x0a, 0x08, 0x53, 0x65, 0x65, 0x64, 0x50, 0x6f, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x53, 0x65,
	0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x73, 0x65, 0x65, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x65, 0x78, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x67,
	0x0a, 0x0c, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x69, 0x67, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x08, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x72, 0x65, 0x71,
	0x75, 0x69, 0x72, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f,
	0x6b, 0x65, 0x79, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x73, 0x22, 0x54, 0x0a, 0x06, 0x53, 0x65, 0x67, 0x77, 0x69,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x50,
	0x72, 0x69, 0x76, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x72,
	0x69, 0x76, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x22, 0x4b, 0x0a,
	0x0e, 0x53, 0x65, 0x67, 0x77, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1f, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x62, 0x74, 0x63, 0x2e, 0x53, 0x65,
	0x67, 0x77, 0x69, 0x74, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3c, 0x0a, 0x08, 0x4d, 0x75,
	0x6c, 0x74, 0x69, 0x53, 0x69, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x16, 0x0a, 0x06, 0x53, 0x63, 0x72, 0x69, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x22, 0x4f, 0x0a, 0x10, 0x4d, 0x75, 0x6c, 0x74,
	0x69, 0x53, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x62, 0x74, 0x63, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x53, 0x69, 0x67, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0xf0, 0x01, 0x0a, 0x0a, 0x42, 0x54,
	0x43, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x09, 0x4e, 0x65, 0x77, 0x53,
	0x65, 0x67, 0x77, 0x69, 0x74, 0x12, 0x0e, 0x2e, 0x62, 0x74, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74,
	0x79, 0x50, 0x6f, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x62, 0x74, 0x63, 0x2e, 0x53, 0x65, 0x67, 0x77,
	0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3e, 0x0a, 0x12,
	0x53, 0x65, 0x67, 0x77, 0x69, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x4d, 0x6e, 0x65, 0x6d, 0x6f, 0x6e,
	0x69, 0x63, 0x12, 0x11, 0x2e, 0x62, 0x74, 0x63, 0x2e, 0x4d, 0x6e, 0x65, 0x6d, 0x6f, 0x6e, 0x69,
	0x63, 0x50, 0x6f, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x62, 0x74, 0x63, 0x2e, 0x53, 0x65, 0x67, 0x77,
	0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0e,
	0x53, 0x65, 0x67, 0x77, 0x69, 0x74, 0x46, 0x72, 0x6f, 0x6d, 0x53, 0x65, 0x65, 0x64, 0x12, 0x0d,
	0x2e, 0x62, 0x74, 0x63, 0x2e, 0x53, 0x65, 0x65, 0x64, 0x50, 0x6f, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x62, 0x74, 0x63, 0x2e, 0x53, 0x65, 0x67, 0x77, 0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x08, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x69, 0x67,
	0x12, 0x11, 0x2e, 0x62, 0x74, 0x63, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53, 0x69, 0x67, 0x50,
	0x6f, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x62, 0x74, 0x63, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x53,
	0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09,
	0x2e, 0x2f, 0x62, 0x74, 0x63, 0x3b, 0x62, 0x74, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_btc_btc_proto_rawDescOnce sync.Once
	file_btc_btc_proto_rawDescData = file_btc_btc_proto_rawDesc
)

func file_btc_btc_proto_rawDescGZIP() []byte {
	file_btc_btc_proto_rawDescOnce.Do(func() {
		file_btc_btc_proto_rawDescData = protoimpl.X.CompressGZIP(file_btc_btc_proto_rawDescData)
	})
	return file_btc_btc_proto_rawDescData
}

var file_btc_btc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_btc_btc_proto_goTypes = []interface{}{
	(*PubKeyPost)(nil),       // 0: btc.PubKeyPost
	(*MnemonicPost)(nil),     // 1: btc.MnemonicPost
	(*SeedPost)(nil),         // 2: btc.SeedPost
	(*MultiSigPost)(nil),     // 3: btc.MultiSigPost
	(*Segwit)(nil),           // 4: btc.Segwit
	(*SegwitResponse)(nil),   // 5: btc.SegwitResponse
	(*MultiSig)(nil),         // 6: btc.MultiSig
	(*MultiSigResponse)(nil), // 7: btc.MultiSigResponse
	(*EmptyPost)(nil),        // 8: btc.EmptyPost
}
var file_btc_btc_proto_depIdxs = []int32{
	4, // 0: btc.SegwitResponse.Data:type_name -> btc.Segwit
	6, // 1: btc.MultiSigResponse.Data:type_name -> btc.MultiSig
	8, // 2: btc.BTCService.NewSegwit:input_type -> btc.EmptyPost
	1, // 3: btc.BTCService.SegwitFromMnemonic:input_type -> btc.MnemonicPost
	2, // 4: btc.BTCService.SegwitFromSeed:input_type -> btc.SeedPost
	3, // 5: btc.BTCService.MultiSig:input_type -> btc.MultiSigPost
	5, // 6: btc.BTCService.NewSegwit:output_type -> btc.SegwitResponse
	5, // 7: btc.BTCService.SegwitFromMnemonic:output_type -> btc.SegwitResponse
	5, // 8: btc.BTCService.SegwitFromSeed:output_type -> btc.SegwitResponse
	7, // 9: btc.BTCService.MultiSig:output_type -> btc.MultiSigResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_btc_btc_proto_init() }
func file_btc_btc_proto_init() {
	if File_btc_btc_proto != nil {
		return
	}
	file_btc_global_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_btc_btc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PubKeyPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_btc_btc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MnemonicPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_btc_btc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeedPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_btc_btc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiSigPost); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_btc_btc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Segwit); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_btc_btc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SegwitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_btc_btc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiSig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_btc_btc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MultiSigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_btc_btc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_btc_btc_proto_goTypes,
		DependencyIndexes: file_btc_btc_proto_depIdxs,
		MessageInfos:      file_btc_btc_proto_msgTypes,
	}.Build()
	File_btc_btc_proto = out.File
	file_btc_btc_proto_rawDesc = nil
	file_btc_btc_proto_goTypes = nil
	file_btc_btc_proto_depIdxs = nil
}
