// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package btc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BTCServiceClient is the client API for BTCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BTCServiceClient interface {
	Segwit(ctx context.Context, in *EmptyPost, opts ...grpc.CallOption) (*StringResponse, error)
	MultiSig(ctx context.Context, in *EmptyPost, opts ...grpc.CallOption) (*StringResponse, error)
}

type bTCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBTCServiceClient(cc grpc.ClientConnInterface) BTCServiceClient {
	return &bTCServiceClient{cc}
}

func (c *bTCServiceClient) Segwit(ctx context.Context, in *EmptyPost, opts ...grpc.CallOption) (*StringResponse, error) {
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, "/btc.BTCService/Segwit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bTCServiceClient) MultiSig(ctx context.Context, in *EmptyPost, opts ...grpc.CallOption) (*StringResponse, error) {
	out := new(StringResponse)
	err := c.cc.Invoke(ctx, "/btc.BTCService/MultiSig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BTCServiceServer is the server API for BTCService service.
// All implementations must embed UnimplementedBTCServiceServer
// for forward compatibility
type BTCServiceServer interface {
	Segwit(context.Context, *EmptyPost) (*StringResponse, error)
	MultiSig(context.Context, *EmptyPost) (*StringResponse, error)
	mustEmbedUnimplementedBTCServiceServer()
}

// UnimplementedBTCServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBTCServiceServer struct {
}

func (UnimplementedBTCServiceServer) Segwit(context.Context, *EmptyPost) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Segwit not implemented")
}
func (UnimplementedBTCServiceServer) MultiSig(context.Context, *EmptyPost) (*StringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MultiSig not implemented")
}
func (UnimplementedBTCServiceServer) mustEmbedUnimplementedBTCServiceServer() {}

// UnsafeBTCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BTCServiceServer will
// result in compilation errors.
type UnsafeBTCServiceServer interface {
	mustEmbedUnimplementedBTCServiceServer()
}

func RegisterBTCServiceServer(s grpc.ServiceRegistrar, srv BTCServiceServer) {
	s.RegisterService(&BTCService_ServiceDesc, srv)
}

func _BTCService_Segwit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyPost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BTCServiceServer).Segwit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/btc.BTCService/Segwit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BTCServiceServer).Segwit(ctx, req.(*EmptyPost))
	}
	return interceptor(ctx, in, info, handler)
}

func _BTCService_MultiSig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyPost)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BTCServiceServer).MultiSig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/btc.BTCService/MultiSig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BTCServiceServer).MultiSig(ctx, req.(*EmptyPost))
	}
	return interceptor(ctx, in, info, handler)
}

// BTCService_ServiceDesc is the grpc.ServiceDesc for BTCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BTCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "btc.BTCService",
	HandlerType: (*BTCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Segwit",
			Handler:    _BTCService_Segwit_Handler,
		},
		{
			MethodName: "MultiSig",
			Handler:    _BTCService_MultiSig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "btc/btc.proto",
}
